### ISSUE TITLE
Queries including + don't go through including the +

### ISSUE THREAD

**Issue by mrhappyma** [punctuations/newtab#13]
Not quite sure how to phrase this so here's a screen recording:
[https://og.blurple.rip/38_AM.webm](https://og.blurple.rip/38_AM.webm)

**Comment by mrhappyma** [comment]
@punctuations
??

**Comment by punctuations** [comment]
It happens while encoding the string into a URI component, will make an exception here, thanks

**Comment by punctuations** [comment]
@mrhappyma so, unfortunately, I cannot make this happen as it is an issue with @alii's search which can be found  @ https://github.com/alii/search

I can create an exception and replace the "+" with "plus", let me know what you think!

**Comment by punctuations** [comment]
Okay! Update: I'm just a tad dumb, I forgot to encode the query, I will rectify this.

Thank you @mrhappyma for bringing this to my attention
